<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/ionicons/css/ionicons.min.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/iCheck/square/blue.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/morris/morris.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/datepicker/datepicker3.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/daterangepicker/daterangepicker.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/datatables/dataTables.bootstrap.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/treeTable/jquery.treetable.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/treeTable/jquery.treetable.theme.default.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/select2/select2.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/colorpicker/bootstrap-colorpicker.min.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/bootstrap-markdown/css/bootstrap-markdown.min.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/adminLTE/css/AdminLTE.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/adminLTE/css/skins/_all-skins.min.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/css/style.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/ionslider/ion.rangeSlider.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/ionslider/ion.rangeSlider.skinNice.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/bootstrap-slider/slider.css">
<link rel="stylesheet" href="<%=pageContext.getServletContext().getContextPath()%>/plugins/bootstrap-datetimepicker/bootstrap-datetimepicker.css">
